/**
 * Entry point for the browser, responsible for hydrating the markup generated by the server
 * in your server entry module.
 * 
 * - Note: Hydrogen requires this file to exist, despite not being required in base Remix.
 *
 * @see https://remix.run/docs/en/main/file-conventions/entry.client
 */
import { RemixBrowser } from '@remix-run/react'
import { startTransition, StrictMode } from 'react'
import { hydrateRoot } from 'react-dom/client'

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RemixBrowser />
    </StrictMode>
  )
})
